# Generated by Django 5.2.16 on 2026-07-18 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientoentrega',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='orders.pedido'),
        ),
        migrations.AddField(
            model_name='seguimientoentrega',
            name='repartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='delivery.repartidor'),
        ),
    ]
