# Generated by Django 5.2.16 on 2026-07-18 02:59

import apps.businesses.domain.horario
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('COMIDA', 'Comida'), ('FARMACIA', 'Farmacia'), ('ABARROTES', 'Abarrotes'), ('BEBIDAS', 'Bebidas'), ('OTROS', 'Otros')], default='COMIDA', max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('horario_json', models.JSONField(blank=True, default=apps.businesses.domain.horario.horario_por_defecto)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('aprobado', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_dueno', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='negocio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ZonaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('distrito', models.CharField(max_length=100)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(help_text='Zona general a la que pertenece el distrito.', on_delete=django.db.models.deletion.PROTECT, related_name='distritos', to='businesses.zona')),
            ],
            options={
                'verbose_name': 'Distrito de entrega',
                'verbose_name_plural': 'Distritos de entrega',
                'ordering': ['zona__nombre', 'distrito'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TarifaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='businesses.negocio')),
                ('zona_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='businesses.zonaentrega')),
            ],
            options={
                'verbose_name': 'Tarifa de envío',
                'verbose_name_plural': 'Tarifas de envío',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='negocio',
            name='zona',
            field=models.ForeignKey(blank=True, help_text='Zona donde se encuentra la dirección del negocio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='negocios', to='businesses.zonaentrega'),
        ),
        migrations.AddConstraint(
            model_name='zona',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('nombre',), name='unique_zona_nombre_activa'),
        ),
        migrations.AddConstraint(
            model_name='zonaentrega',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('zona', 'distrito'), name='unique_distrito_por_zona'),
        ),
        migrations.AddConstraint(
            model_name='tarifaenvio',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('negocio', 'zona_entrega'), name='unique_tarifa_negocio_zona'),
        ),
        migrations.AddConstraint(
            model_name='tarifaenvio',
            constraint=models.CheckConstraint(condition=models.Q(('costo__gte', 0)), name='tarifa_costo_no_negativo'),
        ),
    ]
