# Generated by Django 5.2.16 on 2026-07-18 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zona_entrega',
            field=models.ForeignKey(blank=True, help_text='Distrito del cliente; su zona determina los negocios visibles.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='businesses.zonaentrega'),
        ),
    ]
